Portfolio: desktop version
jerymey/Portfolio-setup pull request #4
Opened 2023-07-13 12:50 UTC by jerymey

**In this project, I did the following:** 

- [ ] Edit HTML and CSS files
- [ ] Used correct GitHub flow
- [ ] Fixed linter errors
- [ ] Added media query for the desktop version

2023-07-13 13:27 UTC, TadesseDev requested changes
### Hi @jerymey 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)




## Highlights
 - [x] Good job overall following the template design ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 13:27 UTC, TadesseDev commented on index.html
> -            <div class="menu-icon">
- [ ] Dear @jerymey, Your navbar navigation items are hidden from the screen for screen sizes from `768px` to `1400px`, Please make sure we can always see the navigation items on the screen and the layout stays the same. 
- [ ] Also the logo is in multi line text, This is different from the original design. Please take a look and make some changes.
### Screen size >768px 
![image](https://github.com/jerymey/Portfolio-setup/assets/69077061/fba791f3-c302-483b-a0cc-140110a41802)

2023-07-13 13:27 UTC, TadesseDev commented on index.html
>          </article>
- [ ] Dear @jerymey, For the buttons, when I hover over the button, I notice the color for the background and text becomes the same, which prevents me from reading the text while hovering over it. Please use the button interaction layout from figma and apply the sma effect.

### Your button on hover 
![image](https://github.com/jerymey/Portfolio-setup/assets/69077061/9a8118f0-9cc3-4b66-a450-f719170fe3b7)

### Figma layout 
![image](https://github.com/jerymey/Portfolio-setup/assets/69077061/e2131cd6-7019-4789-aec1-82d411e24390)

2023-07-13 13:27 UTC, TadesseDev commented on index.html
> +    </div>
- [ ] For the `About Myself` section, Please notice the left one is expected to take 40% and the right one the remaining 60% of the page's width. In your case, I can see both use 50% of the width and this is against the provided design, Please amend this change to the project. 
- [ ] Also, I can see your design overflows for screen size from `768px` to `1400px`, and I have to scroll the overflow to see the whole content. This is not a good practice when it comes to the UI design guideline. Please make sure your design is responsive and stays inside the view port at all time.

### Your design 
![image](https://github.com/jerymey/Portfolio-setup/assets/69077061/51c406c9-5ff4-4bf9-9431-eb90b4989385)

### Figma design 
![image](https://github.com/jerymey/Portfolio-setup/assets/69077061/08e0e2cc-7f32-43be-ab69-4fb92a52f23f)

2023-07-13 13:27 UTC, TadesseDev commented on index.html
>          </footer>
- [ ] For the contact form, Please make sure all the elements of the form are centered on the page. I noticed your design is centered on some screen sizes and not on others. in order to clone the design we need to make sure all the content are centered on all the desktop screen sizes.

### Your design 
![image](https://github.com/jerymey/Portfolio-setup/assets/69077061/0e928014-4537-47ec-b7ed-5cea0669f674)

2023-07-14 15:17 UTC, Alfredbis29 approved these changes
# STATUS: APPROVED   
 ## Hi  @jerymey 
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Good Job :+1: :smile: 
 
 Now you can merge this branch and move on 1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
 
 ## Optional suggestions

- [x] Check Under The Review

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 15:17 UTC, Alfredbis29 commented on index.html
>        <Section class="about-myself">
- [OPTIONAL ] I can see that you made a great design for this project but there are something little things you should work on for your project to look more professional, Compare your design to the Figma one, the arrows should have space between your languages' cards, kindly fix this for your project to match the Figma design. check this :point_down: 
![Screenshot from 2023-07-14 17-01-48](https://github.com/jerymey/Portfolio-setup/assets/88894525/ad3f5e11-53f0-48f0-bd48-5aceb6e12acf)
Figma Design 
 ![image](https://user-images.githubusercontent.com/69077061/253288803-08e0e2cc-7f32-43be-ab69-4fb92a52f23f.png)

2023-07-17 09:34 UTC, merged